/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#777587",
        "surface-container": "#efecf9",
        "on-primary-fixed-variant": "#3124cb",
        "on-secondary-fixed-variant": "#3c389d",
        "on-tertiary-fixed-variant": "#812800",
        "secondary-fixed": "#e2dfff",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e4e1ee",
        "tertiary-fixed-dim": "#ffb59b",
        "error": "#ba1a1a",
        "surface": "#fcf8ff",
        "on-primary-fixed": "#0c006a",
        "surface-dim": "#dbd8e5",
        "on-background": "#1b1b24",
        "primary-fixed-dim": "#c2c1ff",
        "primary": "#250fc2",
        "on-secondary-fixed": "#0e006a",
        "tertiary": "#712200",
        "on-secondary-container": "#2c268d",
        "tertiary-container": "#983100",
        "primary-fixed": "#e2dfff",
        "surface-bright": "#fcf8ff",
        "surface-variant": "#e4e1ee",
        "on-tertiary-fixed": "#380d00",
        "secondary-fixed-dim": "#c3c0ff",
        "primary-container": "#4038d8",
        "on-secondary": "#ffffff",
        "on-surface": "#1b1b24",
        "inverse-primary": "#c2c1ff",
        "background": "#fcf8ff",
        "inverse-surface": "#302f39",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-primary-container": "#c5c3ff",
        "secondary-container": "#9795fe",
        "surface-container-low": "#f5f2ff",
        "outline-variant": "#c7c4d8",
        "surface-container-high": "#eae6f3",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f2effc",
        "secondary": "#5452b6",
        "surface-tint": "#4b45e2",
        "on-surface-variant": "#464555",
        "on-tertiary-container": "#ffb8a0",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdbcf"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "gutter": "24px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "unit": "4px"
      },
      fontFamily: {
        "headline-md": ["Space Mono", "monospace"],
        "label-caps": ["Space Mono", "monospace"],
        "headline-sm": ["Space Mono", "monospace"],
        "metadata": ["Space Mono", "monospace"],
        "body-lg": ["Space Mono", "monospace"],
        "headline-lg": ["Space Mono", "monospace"],
        "body-md": ["Space Mono", "monospace"],
        "sans": ["Space Mono", "monospace"] // Fallback for global
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "headline-sm": ["18px", { "lineHeight": "1.4", "fontWeight": "700" }],
        "metadata": ["11px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
